version: "3"
services:

  db:
    image: mysql:8.0.2
    environment:
      MYSQL_DATABASE: usersDB
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: eszkis
      MYSQL_PASSWORD: password
    ports:
      - "8080:3306"

  web:
    build: .  
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db